### ISSUE TITLE
Problem with initial install

### ISSUE THREAD

**Issue by tfonias74** [GAM-team/got-your-back#334]
The issue tracker is for reporting product deficiencies. How do I questions should be posted to the discussion forum at https://groups.google.com/group/got-your-back. When in doubt, start at the discussion forum and return here only when instructed to do so.

Please confirm the following:
* I have upgraded to the latest GYB release from https://github.com/jay0lee/got-your-back/releases and I still have this issue.
* I am typing the command as described in the GAM Wiki at https://github.com/jay0lee/got-your-back/wiki
Yes

Full steps to reproduce the issue:
1. 
2.
3.

Expected outcome (what are you trying to do?):
In the authorization, after project, I created a service account and then OAuth 2.0 Client IDs and provided that to the program.
Then at the authorization part for backup in the page that I am required to access I choose account and then it requires an admin.
I think I may have done something wrong. Now I have deleted the credentials and would like to repeat that part (not everything).
Is it possible? If not what is the required procedure?

Actual outcome (what errors or bad behavior do you see instead?):

**Comment by jay0lee** [comment]
Service account setup is for Google Workspace admins only. If you're using GYB for @gmail.com accounts don't follow those steps. If you need help, use the mailing list, not the issue tracker please:

https://groups.google.com/g/got-your-back
