### ISSUE TITLE
Selectively delete some emails from Gmail mailbox

### ISSUE THREAD

**Issue by hongyi-zhao** [GAM-team/got-your-back#335]
At present, there are a lot of emails in my Gmail inbox. I want to delete some of them according to specific filters, for example, deleting the ones not written by or posted to me myself. 

I'm not sure whether this project can help me finish the work.

Regards,
HZ

**Comment by jay0lee** [comment]
Please post this to the discussion group rather than the issue tracker 

https://groups.google.com/g/got-your-back

**Comment by hongyi-zhao** [comment]
I've just posted this question on it, but it seems the question can't appear there immediately.
