### ISSUE TITLE
400: Invalid label name - invalidArgument

### ISSUE THREAD

**Issue by mansj** [GAM-team/got-your-back#350]
I am running this command, on a 24GB large backup from G Suite: 

bin/gyb/gyb --email myaddress@gmail.com --action restore-mbox --local-folder ~/Desktop/

After 24 hours and 30.6% I get this message:

Creating label Muted                                                            
400: Invalid label name - invalidArgument

And the program crashes/finishes so I can't continue. 

Any advice?

**Comment by jay0lee** [comment]
Muted is a reserved label name that you can't restore or use with Gmail API. Try adding:

```--extra-reserved-labels muted```

to your command to tell GYB not to try and create/use the label. I've added this for the next version also.

**Comment by mansj** [comment]
Wow, thank you for the quick response, and it did indeed work to add the reserved label. Thank you.
