### ISSUE TITLE
Does not work with Gmail in Spanish because words like "leídos"

### ISSUE THREAD

**Issue by MiguelElGallo** [GAM-team/got-your-back#360]
Hi,
Trying to do a restore it fails with: (from a MBOX file created by Google Take out)

Creating label No leídos                                                        
400: Invalid label name - invalidArgument

This No léidos means, not read.

Any ideas what to do?
Thanks,
MIguel

**Comment by jay0lee** [comment]
Try adding the argument:
```
--extra-reserved-labels "No léidos"
```
