### ISSUE TITLE
New Windows installation, project creation fails with "multiprocessing-fork" error

### ISSUE THREAD

**Issue by spyguitar** [GAM-team/got-your-back#365]
* I have upgraded to the latest GYB release from https://github.com/jay0lee/got-your-back/releases and I still have this issue.
--CONFIRMED, running GYB 1.60 
* I am typing the command as described in the GAM Wiki at https://github.com/jay0lee/got-your-back/wiki
--CONFIRMED

- Running on Windows Server 2019, version 10.0.17763
- Also tested with the same behavior on Windows 10 Pro, version 10.0.19044

Full steps to reproduce the issue:
1. Download and install GYB from https://github.com/GAM-team/got-your-back/releases/download/v1.60/gyb-1.60-windows-x86_64.msi
2. C:\gyb\gyb-setup-bat launches automatically, and I enter my email address, OR
3. run `c:\gyb\gyb --action create-project --email [Google email address]`

Expected outcome (what are you trying to do?):

- The Google authentication flow should happen and I should be able to create my project.

Actual outcome (what errors or bad behavior do you see instead?):

- `gyb.exe: error: unrecognized arguments: --multiprocessing-fork parent_pid=2484 pipe_handle=752`
- at this point, I can only CTRL+C to get out, or close the cmd window

Looking at Process Explorer, 2484 is the PID of GYB.exe; it has three NamedPipe handles, two of which are called "\Device\NamedPipe\pyc-2484-0-sv13popd". I checked the discussion group and this hasn't been mentioned yet; a quick Google search indicates this might be something wrong with the way Python for Windows is implementing multiprocessing.

**Comment by dantasfiles** [comment]
Same issue on Windows 11 Home Version 10.0.22000
