### ISSUE TITLE
Error when trying to upgrade to the latest release.

### ISSUE THREAD

**Issue by typeraj** [GAM-team/got-your-back#366]
Full steps to reproduce the issue:
1. Run the upgrade command as described in the wiik
2. Tried this on 2 different instances of GYB on running on different machines.

Expected outcome (what are you trying to do?): upgrade to the latest release. 

Actual outcome (what errors or bad behavior do you see instead?): see attached screenshot: 
![Screen Shot 2022-04-01 at 08 58 42](https://user-images.githubusercontent.com/6182364/161156225-30911beb-45ab-4557-98c7-f7ee00a7c5ea.png)

**Comment by SkullnBones19** [comment]
I am getting the same error. I am installing it for the first time.
![Screen Shot 2022-04-01 at 2 26 43 PM](https://user-images.githubusercontent.com/102833569/161343490-3b1cbf48-4588-41bf-bcac-9a3b0a0ef2e4.png)

**Comment by jay0lee** [comment]
This should be fixed now, please try again.
