### ISSUE TITLE
Google will disallow OAuth Out-of-band

### ISSUE THREAD

**Issue by centic9** [GAM-team/got-your-back#374]
I received an email from Google stating that **OAuth Out-of-band** will be disabled sometimes later this year.

I don't know much about OAuth, but I found `'redirect_uris': ['http://localhost', 'urn:ietf:wg:oauth:2.0:oob'],` in the sources, which indicates to me that GYB is using this mechanism and thus is affected.

See https://developers.googleblog.com/2022/02/making-oauth-flows-safer.html#disallowed-oob

Is there a way to switch GYB to a different authentication flow?

**Comment by bryantech** [comment]
So long and thanks for all the fish. I kid. I am sure Jay will figure out a solution.

**Comment by centic9** [comment]
Ah, do you think the two URIs for `redirect_uris` mean OOB is only used as fallback if localhost is not working?

**Comment by jay0lee** [comment]
https://groups.google.com/g/got-your-back/c/w0cT19cSKx0

**Comment by AlfredJKwack** [comment]
Hi. When ugrading to [GYB 1.60](https://github.com/GAM-team/got-your-back/releases/tag/v1.60), aside from upgrading the installation [as per the wiki instructions](https://github.com/GAM-team/got-your-back/wiki#upgrading-gyb) I'm assuming that there's a few more things that need to be done right to migrate to the new Authentication mechanisms from google

Could someone chime in here (or update the wiki) with a specific  "how to upgrade to [GYB 1.60](https://github.com/GAM-team/got-your-back/releases/tag/v1.60)"guide?

**Comment by jay0lee** [comment]
Nope. Just upgrade.

**Comment by AlfredJKwack** [comment]
Thanks!
