### ISSUE TITLE
Error 403: org_internal

### ISSUE THREAD

**Issue by Craigp23** [GAM-team/got-your-back#389]
Hi, I'm using GYB for the first time. 

Trying a backup mail from a Google Workspace account to my new gmail.com account. The backup appears to have completed successfully. However, when I ran :

`gyb --email newaddress@gmail.com --action restore --local-folder GYB-GMail-Backup-oldaddress@gmail.com`

substituting `newaddress@gmail.com` and `oldaddress@gmail.com` with the actual addresses, a browser page opened, prompted for address and password, and then displayed:

**Authorisation Error**

Error 403: org_internal

This client is restricted to users within its organization.

Request Details
The content in this section has been provided by the app developer. This content has not been reviewed or verified by Google.
If you’re the app developer, make sure that these request details comply with Google policies.
access_type: offline
login_hint: ****************@gmail.com
response_type: code
redirect_uri: http://127.0.0.1:8080/
state: tyKDfh2Elb8AGbynPYqsvM7i0Wacoc
code_challenge_method: S256
client_id: *****************************
code_challenge: *********************************
scope: https://www.googleapis.com/auth/userinfo.email https://mail.google.com/ https://www.googleapis.com/auth/apps.groups.migration https://www.googleapis.com/auth/drive.appdata openid

Any tips on how best to proceed are much appreciated  :)

**Comment by NoSubstitute** [comment]
You need to set up GYB for your private Gmail account separately.

**_Remember to first move/backup your JSON files from the Workspace setup!_**

**Comment by Craigp23** [comment]
Thank you! :) I'll try that and report back here
