### ISSUE TITLE
Many VirusTotal vendors flagging GYB as Trojan

### ISSUE THREAD

**Issue by lwcorp** [GAM-team/got-your-back#396]
The issue tracker is for reporting product deficiencies. How do I questions should be posted to the discussion forum at https://groups.google.com/group/got-your-back. When in doubt, start at the discussion forum and return here only when instructed to do so.

Please confirm the following:
* I have upgraded to the latest GYB release from https://github.com/jay0lee/got-your-back/releases and I still have this issue. **Yes**
* I am typing the command as described in the GAM Wiki at https://github.com/jay0lee/got-your-back/wiki **Yes**

Full steps to reproduce the issue:
1. Download gyb-1.70-windows-x86_64.zip, gyb-1.70-windows-x86_64.msi and/or gyb-1.70-linux-aarch64-glibc2.35.tar.xz
1. Upload each of them to https://www.virustotal.com
1. Observe the results

Expected outcome (what are you trying to do?):
Get 2-3 accusations at max, but hopefully 0.

Actual outcome (what errors or bad behavior do you see instead?):
1. Get up to 14 complains - see [this](https://www.virustotal.com/gui/file/e9a0a1493e2bfbb094ff3594d35a7f9ecd90336fa0844b9f71853ec81c74dde0/detection), [that](https://www.virustotal.com/gui/file/2eafc7ae769c792342d1d2e3e9d073364101f477b62f03e16b281005142e8347/detection) and also [this](https://www.virustotal.com/gui/file/63a039ef89904b65715e3011c28c357b39db982e693b5c04cb64f8b3bf55af58).
1. **Get your Internet connection blocked if you use SentinelOne**.

I know it's similar to #341 but this time it's much worse.
Why so many complaints and why **trojan**?
This program largely appeals to workplaces which might stop using it because if it, even though we all love the program. Actual outcome 2 was a very unpleasant experience.

![image](https://user-images.githubusercontent.com/1773306/188289181-022ab422-d110-427e-8c71-cb94fb380fc3.png)

![image](https://user-images.githubusercontent.com/1773306/188289185-1da9db2c-a3ed-4c76-9174-cd170d78958e.png)

![image](https://user-images.githubusercontent.com/1773306/188289189-0b47588d-a00c-40eb-ae7a-748edd21c9b5.png)

**Comment by jay0lee** [comment]
This isn't something GYB can totally control, AV vendors are simply overly aggressive in identifying these free tools as malware. However some tweaks in 1.71 may at least reduce the frequency of detection here.

**Comment by bryantech** [comment]
Yeah I'm getting the same thing I went back to 1.62 and I'm not having as
many virus deletions from virus software. Absolutely love this software
he's at all the time.

**Comment by lwcorp** [comment]
I indeed see less detections now, thanks! Workplaces don't care if it's outside the control of GYB, they just block the entire workstation. If more detections come up, you can always approach each and every of these vendors and submit a false positive report. It's not nice but that's reality.

**Comment by quack79** [comment]
I had to add gyb as an exception in TotalAV as it quarantined it.

**Comment by dlong500** [comment]
Unfortunately the latest version (1.95) is now being flagged by Microsoft Windows Defender (which is arguably worse than random third party AV false detections since it's built-in to Windows).  I'm seeing the msi file hash show up on VirusTotal with ONLY Windows Defender flagging it as `Trojan:Win32/Malgent!MSR`
