### ISSUE TITLE
label-restored not applying on restore-group action

### ISSUE THREAD

**Issue by bfourgeaud** [GAM-team/got-your-back#417]
Labels are not created on restored emails for groups with the flag `--label-restored` and `--action restore-group`

**Full steps to reproduce the issue:**

1. Create a folder /archives containing a .mbox file
2. Run the backup command to backup these emails to a google group : `gyb --email [group-email] --service-account --use-admin [admin-email] --action restore-group --local-folder ./archives --label-restored "ARCHIVE"`

**Expected outcome (what are you trying to do?):**
The imported emails should be labelled `ARCHIVE`

**Actual outcome (what errors or bad behavior do you see instead?):**
No label is applied. I tried it with already existing labels and new Labels. Same outcome.

**Comment by jay0lee** [comment]
This is working as expected, the Google Groups Migration API does not support applying group labels to migrated messages, that can only be used when restoring to a Gmail mailbox.
