### ISSUE TITLE
Metadata can not be read from new google Vault export format

### ISSUE THREAD

**Issue by TimetravelerDD** [GAM-team/got-your-back#420]
# Intro
google vault has a new default export format for meta data which now gives you a csv file instead of XML

On top of that the errors file now uses xml instead of CSV so GYB is currently trying to read the wrong file

https://support.google.com/vault/answer/4388708?hl=en&visit_id=638150245468213825-2609647667&p=new_gmail_export&rd=1#new_gmail_export&zippy=%2Cdecember-updated-ui-for-future-client-side-encryption-functionality%2Cfebruary-new-gmail-export-system-available

https://support.google.com/vault/answer/6099459?hl=en#gmail_contents&gmail_metadata&gmail_count&#gmail_error_new&gmail_count&gmail_export&mailxml&metadata_csv&drive_export&drivexml&metadata&voice_export&voice_xml&gmail_error&chat_error&drive_error&voice_error&zippy=%2Cexport-contents%2Cmessage-parameters-in-the-metadata-file%2Cinformation-in-the-count-file

it seems the old format can not be downloaded anymore online and is available only via the API for a limited time.

It would be great if GYB could support both formats to keep old exports functional

### Please confirm the following:
* I have upgraded to the latest GYB release from https://github.com/jay0lee/got-your-back/releases and I still have this issue.
* I am typing the command as described in the GAM Wiki at https://github.com/jay0lee/got-your-back/wiki

### Full steps to reproduce the issue:
1.  download an export from google vault https://vault.google.com/matter/
2. run GYB with `--action restore-mbox` and  `--local-folder`

### Expected outcome (what are you trying to do?):
GYB is importing the Metadata file

### Actual outcome (what errors or bad behavior do you see instead?):
GYB tried to read the error file
```
Reading Vault labels from 442b file test\test-errors.xml
large files may take some time to read...
```

# Original Announcement from google
<html>
<body>
<p style="color: rgb(211, 207, 201); font-family: Arial, Helvetica, sans-serif; font-size: small; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(24, 26, 27); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">We are writing to let you know about upcoming changes to the<span> </span><span class="il">Vault</span><span> </span>API, which may require informing your Google Workspace customers who use the Google<span> </span><span class="il">Vault</span><span> </span>API directly, or use any 3rd party tool that relies on the<span> </span><span class="il">Vault</span><span> </span>API.</p><p style="color: rgb(211, 207, 201); font-family: Arial, Helvetica, sans-serif; font-size: small; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(24, 26, 27); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">On<span> </span><strong>February 24, 2022</strong><span> </span>we introduced a new export pipeline for Gmail data, which also introduced changes to the file formats of several metadata files (<a href="https://notifications.google.com/g/p/AM0Oveqwr1n3KFua-Oik6M1cmW9Fq7fe9NaPu03zGPVY1C23AKXy2JggrcGjsLmNwdu9PnzOdutyGoRn3uZasEMNDQnglo2vN_zCK884N-KDt5ncA2ybFGCA8q-jfKC1-r6Ft-L2VTfc091QVC_eIbkwjtSGC38t0wXHm5C13me7MmSmng34rLUWDeyHYEL3wI9Tk_KcoPYveO9uyubfRxkMb-cHvZtyX-5OH5hTQMRGP5veDiT9-lvIDWvwDeSjysJXbg6U_I2ehiq-XR3sBaysG8570MVPj80y-Bu1fAvgrWrCIxuLb5MKB-uN" target="_blank" data-saferedirecturl="https://www.google.com/url?q=https://notifications.google.com/g/p/AM0Oveqwr1n3KFua-Oik6M1cmW9Fq7fe9NaPu03zGPVY1C23AKXy2JggrcGjsLmNwdu9PnzOdutyGoRn3uZasEMNDQnglo2vN_zCK884N-KDt5ncA2ybFGCA8q-jfKC1-r6Ft-L2VTfc091QVC_eIbkwjtSGC38t0wXHm5C13me7MmSmng34rLUWDeyHYEL3wI9Tk_KcoPYveO9uyubfRxkMb-cHvZtyX-5OH5hTQMRGP5veDiT9-lvIDWvwDeSjysJXbg6U_I2ehiq-XR3sBaysG8570MVPj80y-Bu1fAvgrWrCIxuLb5MKB-uN&amp;source=gmail&amp;ust=1679515039194000&amp;usg=AOvVaw1Rr2CDETa0JxZflmzfapoK" style="color: rgb(86, 163, 241);">New Gmail export system available</a>). As part of that release we provided users with the ability in the user interface and in the API to select the old pipeline or the new pipeline for generating Gmail exports.</p><h3 style="color: rgb(211, 207, 201); font-family: Arial, Helvetica, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(24, 26, 27); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">What does this mean for my customers?</h3><p style="color: rgb(211, 207, 201); font-family: Arial, Helvetica, sans-serif; font-size: small; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(24, 26, 27); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Starting on<span> </span><strong>January 22, 2024,</strong><span> </span>we will retire the old Gmail export pipeline and only operate the new Gmail export pipeline. If your customers are using the<span> </span><span class="il">Vault</span><span> </span>API or any 3rd party tool that relies on the<span> </span><span class="il">Vault</span><span> </span>API, then starting on<span> </span><strong>January 22, 2024</strong><span> </span>the “<a href="https://notifications.google.com/g/p/AM0OveqY4t2hnUdVfcfFFaKH2GFXutF1TMS4EoAmuxyp5Dc-ONMzbxN4-WgEEPj5OFAegUTb6QIpIrBeECXKPnuPxTgc_pExN8enLlCLYBN3U_Xyevl3sEGs-ATDGjtz8XhKLW_hC1U7b-6w0MT6hhChEVOvDGnrZsMZnWecm00WoskwsymfdJyU5fNl3FGeaSvc8hpHrkrz18dHksS1QczAFV2wEP6JBfedzfZ3GupKeAFt2RYy6QkGzmN4-LHk7zEyxu4TSFBZ" target="_blank" data-saferedirecturl="https://www.google.com/url?q=https://notifications.google.com/g/p/AM0OveqY4t2hnUdVfcfFFaKH2GFXutF1TMS4EoAmuxyp5Dc-ONMzbxN4-WgEEPj5OFAegUTb6QIpIrBeECXKPnuPxTgc_pExN8enLlCLYBN3U_Xyevl3sEGs-ATDGjtz8XhKLW_hC1U7b-6w0MT6hhChEVOvDGnrZsMZnWecm00WoskwsymfdJyU5fNl3FGeaSvc8hpHrkrz18dHksS1QczAFV2wEP6JBfedzfZ3GupKeAFt2RYy6QkGzmN4-LHk7zEyxu4TSFBZ&amp;source=gmail&amp;ust=1679515039194000&amp;usg=AOvVaw3jW-4dDVpwcCGs5UP1a5xC" style="color: rgb(86, 163, 241);">MailExportOptions</a>” setting for “useNewExport” will always be set to<span> </span><strong>True</strong>, regardless of the value that you set in the API call.</p><p style="color: rgb(211, 207, 201); font-family: Arial, Helvetica, sans-serif; font-size: small; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(24, 26, 27); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Therefore the files that are returned from a Gmail export will be returned in csv format instead of the old xml format in the previous version. You can find the details about the format changes in the<span> </span><a href="https://notifications.google.com/g/p/AM0Ovep4GJyCIy_A784pEn3uQ2NbnduQr9h5KvAx3cv_MIC0wem6xYJA13UIFEaXZ9LK3amOrbhhq8h_cp4Xi45r8TanZSxDQTJQKVl8WE90r0wVOzCoF2tFPRgYNwdB2aBgLpA-NnTln_hFenEW2TSiGaMXdHmKczpRtgB54VAeZ6VJnU4hYfVVqfG3lOa4ctbjUmzoMQvQEO1MOo0GdpBw6QfJwCdNskaBkvuyxsVeuKeAERDlp55Kxu4v3v3x3ELI23fG_VnSqxj9uGurnpdh" target="_blank" data-saferedirecturl="https://www.google.com/url?q=https://notifications.google.com/g/p/AM0Ovep4GJyCIy_A784pEn3uQ2NbnduQr9h5KvAx3cv_MIC0wem6xYJA13UIFEaXZ9LK3amOrbhhq8h_cp4Xi45r8TanZSxDQTJQKVl8WE90r0wVOzCoF2tFPRgYNwdB2aBgLpA-NnTln_hFenEW2TSiGaMXdHmKczpRtgB54VAeZ6VJnU4hYfVVqfG3lOa4ctbjUmzoMQvQEO1MOo0GdpBw6QfJwCdNskaBkvuyxsVeuKeAERDlp55Kxu4v3v3x3ELI23fG_VnSqxj9uGurnpdh&amp;source=gmail&amp;ust=1679515039194000&amp;usg=AOvVaw3Pm5HigKXPac_X3_BOgaxK" style="color: rgb(86, 163, 241);"><span class="il">Vault</span><span> </span>help center article</a><span> </span>concerning “Gmail (new export)” and share that with your customer.</p><h3 style="color: rgb(211, 207, 201); font-family: Arial, Helvetica, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(24, 26, 27); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">What do I need to do?</h3><p style="color: rgb(211, 207, 201); font-family: Arial, Helvetica, sans-serif; font-size: small; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(24, 26, 27); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">If your customers’ applications that use the<span> </span><span class="il">Vault</span><span> </span>API rely on these files to be returned in the XML format,<span> </span><strong>they will need to modify their application code to process the new csv format instead, or contact their respective 3rd party vendor to inquire about the vendor’s plans.</strong><span> </span>They should also forward this email to their vendor for context. Here are the exact changes to the export output.</p><div style="color: rgb(211, 207, 201); font-family: Arial, Helvetica, sans-serif; font-size: small; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(24, 26, 27); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">

Information | Old Gmail export pipeline | New Gmail export pipeline | Changes
-- | -- | -- | --
Message contents | export_name-N.zip | export_name-N.zip | Multiple zip files logic changes (see help center for examples)
Google groups membership information | export_name-group-membership.csv | - | Group member file no longer available
Message metadata | export_name-metadata.xmlexport_name-metadata.csv | export_name-metadata.csv | Xml file is no longer available
Accounts and message count | export_name-result-counts.csv | export_name-result-counts.csv | No changes
Error reports | error.csvexport_name–account-exceptions.csv (Gmail exports)export_name–failed-group-membership-lookups.csv (Groups exports) | export_name-errors.xml | Format change from csv to xml and consolidated to one file
Messages that didn't convert to PST | - | export_name-conversion_errors-N.zip | New error file introduced
File checksums | File checksums | File checksums | No changes

</div>
</body>
</html>

**Comment by gabrielwhite** [comment]
From the announcement:

"Starting on February 2, 2024, we will retire the old Gmail export pipeline and only operate the new Gmail export pipeline. If your customers are using the Vault API or any 3rd party tool that relies on the Vault API, then starting on February 2, 2024 the “MailExportOptions” setting for “useNewExport” will always be set to True, regardless of the value that you set in the API call."

Documentation here: https://support.google.com/vault/answer/6099459?sjid=9304153788799510769-AP#gmail_new&zippy=%2Cexport-contents

**Comment by jay0lee** [comment]
GYB 1.80 (released today) adds support for the new format. Please test and confirm it works for you.

**Comment by gabrielwhite** [comment]
Thanks @jay0lee! The first run seemed to take a very long time (even on fast-incremental) - is there some database being rebuilt as part of this change? Subsequent runs on fast-incremental were fast.

**Comment by jay0lee** [comment]
Not sure what you mean. Fast incremental is for backup not restore.

Where is it taking a long time? What's showing in the output?

**Comment by gabrielwhite** [comment]
Mmm. Maybe an unrelated issue then. I upgraded the script, and then ran to check it worked, and the runtime was considerably longer than when I've tested an upgrade in the past. But all worked.
