### ISSUE TITLE
Slow Upload

### ISSUE THREAD

**Issue by gustavohellwig** [GAM-team/got-your-back#436]
Hi,
The download of the emails is very fast, but the upload is very slow.
For 4.5Gb, it took 9 hours. Is that what is expected?

The internet bandwidth is not a problem.

**Comment by jay0lee** [comment]
Yes, write is slower than read, that's just how it goes.

Total mail size is not terribly relevant, message count is the more important stat. You can generally expect writing to occur at a rate of one message every 2-3 seconds.

Jay

**Comment by gustavohellwig** [comment]
OK. thank you.
