### ISSUE TITLE
NO, it does not work. too many issues and bugs. it almost messed up my google account.

### ISSUE THREAD

**Issue by neonanotux** [GAM-team/got-your-back#481]
NO, it does not work. too many issues and bugs. it almost messed up my google account.NO, it does not work. too many issues and bugs. it almost messed up my google account.

**Comment by jay0lee** [comment]
Closing for lack of any detail. If you need help please reach out in the discussion group with full details of what you tried and what issues you saw.

https://groups.google.com/g/got-your-back

Jay
