### ISSUE TITLE
My Power Went Out During a Very Large Restore... Will this pickup where it left off?

### ISSUE THREAD

**Issue by kendoori** [GAM-team/got-your-back#482]
The issue tracker is for reporting product deficiencies. How do I questions should be posted to the discussion forum at https://groups.google.com/group/got-your-back. When in doubt, start at the discussion forum and return here only when instructed to do so.

Please confirm the following:
* I have upgraded to the latest GYB release from https://github.com/jay0lee/got-your-back/releases and I still have this issue.
* I am typing the command as described in the GAM Wiki at https://github.com/jay0lee/got-your-back/wiki

Full steps to reproduce the issue:
1. gyb --email me@mynewaccount.com --action restore --local-folder /Users/kenny/GYB-GMail-Backup-me@myoldaccount.com --label-restored “Restored-Label”
2.Restore starts and gets about 1/2 way through:  (84944/132763)
3. Power goes out and system closes

Expected outcome (what are you trying to do?):

Finish the process without duplicating what's been done

Actual outcome (what errors or bad behavior do you see instead?):

Not sure. Need to make sure I won't duplicate the initial 84,944 message

**Comment by jay0lee** [comment]
Yes, it will pick up where it left off. Please also use the group for this kind of question in the future.
